# frontend/docker-compose.yml
version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - auto-parts-network

networks:
  auto-parts-network:
    external: true