# backend/docker-compose.yml
version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=auto_parts_db
      - JWT_SECRET="c5b2b14d9ead1242f61dd0978e9877b53e42a679734b2525a77e93c93f0021ca4025cac8d14536a6ae83c847dde7e16bda8ec49d7ed4ca98ceb351413437eae5"
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    depends_on:
      - mysql
    networks:
      - auto-parts-network

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=auto_parts_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - auto-parts-network

volumes:
  mysql_data:

networks:
  auto-parts-network:
    driver: bridge